spring.application.name=streamnotify
# DB接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/streamnotify
spring.datasource.username=streamnotify
spring.datasource.password=streamnotify

# JPA設定
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway設定
spring.flyway.enabled=true
# Twitch OIDC設定
spring.security.oauth2.client.registration.twitch.client-id=${TWITCH_CLIENT_ID}
spring.security.oauth2.client.registration.twitch.client-secret=${TWITCH_CLIENT_SECRET}
spring.security.oauth2.client.registration.twitch.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.twitch.redirect-uri=http://localhost:8080/login/oauth2/code/twitch
spring.security.oauth2.client.registration.twitch.scope=openid
spring.security.oauth2.client.registration.twitch.client-authentication-method=client_secret_post

spring.security.oauth2.client.provider.twitch.authorization-uri=https://id.twitch.tv/oauth2/authorize
spring.security.oauth2.client.provider.twitch.token-uri=https://id.twitch.tv/oauth2/token
spring.security.oauth2.client.provider.twitch.jwk-set-uri=https://id.twitch.tv/oauth2/keys
spring.security.oauth2.client.provider.twitch.user-name-attribute=sub

twitch.eventsub.secret=${TWITCH_EVENTSUB_SECRET}

twitch.eventsub.callback-url=https://barman-angelfish-properly.ngrok-free.dev/webhooks/twitch